name: CI

on:
  push:
    branches:
      - main

jobs:
  secretlint:
    name: Secretlint
    runs-on: ubuntu-latest
    steps:
     - name: sleep
       run: sleep 20
     - name: failure
       run: exit 1

